export const testData = [
    {
     "cardId": "SWSH04-Vivid-Voltage-Weedle-001",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 226360,
     "name": "Weedle",
     "expIdTCGP": "SWSH04 Vivid Voltage",
     "expName": "Vivid Voltage",
     "expCardNumber": "001",
     "expCodeTCGP": "SWSH04",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/226360.jpg",
     "price": 0.03,
     "description": "",
     "releaseDate": "2020-11-13T00:00:00Z",
     "energyType": "Grass",
     "cardType": "Pokemon",
     "pokedex": 13,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH04-Vivid-Voltage-Kakuna-002",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 226361,
     "name": "Kakuna",
     "expIdTCGP": "SWSH04 Vivid Voltage",
     "expName": "Vivid Voltage",
     "expCardNumber": "002",
     "expCodeTCGP": "SWSH04",
     "rarity": "Uncommon",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/226361.jpg",
     "price": 0.03,
     "description": "",
     "releaseDate": "2020-11-13T00:00:00Z",
     "energyType": "Grass",
     "cardType": "Pokemon",
     "pokedex": 14,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH04-Vivid-Voltage-Beedrill-003",
     "collection": "Extra",
     "variant": "Holofoil",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 226362,
     "name": "Beedrill",
     "expIdTCGP": "SWSH04 Vivid Voltage",
     "expName": "Vivid Voltage",
     "expCardNumber": "003",
     "expCodeTCGP": "SWSH04",
     "rarity": "Rare",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/226362.jpg",
     "price": 0.14,
     "description": "<strong>Ability — Elusive Master</strong>\r\n<br>Once during your turn <em>(before your attack)</em>, if this Pokémon is the last card in your hand, you may play it onto your Bench. If you do, draw 3 cards.",
     "releaseDate": "2020-11-13T00:00:00Z",
     "energyType": "Grass",
     "cardType": "Pokemon",
     "pokedex": 15,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH07-Evolving-Skies-Pikachu-049",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 246881,
     "name": "Pikachu",
     "expIdTCGP": "SWSH07 Evolving Skies",
     "expName": "Evolving Skies",
     "expCardNumber": "049",
     "expCodeTCGP": "SWSH07",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/246881.jpg",
     "price": 0.06,
     "description": "",
     "releaseDate": "2021-08-27T00:00:00Z",
     "energyType": "Lightning",
     "cardType": "Pokemon",
     "pokedex": 25,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH02-Rebel-Clash-Clefairy-074",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 213160,
     "name": "Clefairy",
     "expIdTCGP": "SWSH02 Rebel Clash",
     "expName": "Rebel Clash",
     "expCardNumber": "074",
     "expCodeTCGP": "SWSH02",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/213160.jpg",
     "price": 0.07,
     "description": "",
     "releaseDate": "2020-05-01T00:00:00Z",
     "energyType": "Psychic",
     "cardType": "Pokemon",
     "pokedex": 35,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH04-Vivid-Voltage-Clefairy-063",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 226461,
     "name": "Clefairy",
     "expIdTCGP": "SWSH04 Vivid Voltage",
     "expName": "Vivid Voltage",
     "expCardNumber": "063",
     "expCodeTCGP": "SWSH04",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/226461.jpg",
     "price": 0.04,
     "description": "",
     "releaseDate": "2020-11-13T00:00:00Z",
     "energyType": "Psychic",
     "cardType": "Pokemon",
     "pokedex": 35,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH08-Fusion-Strike-Jigglypuff-110",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 253268,
     "name": "Jigglypuff",
     "expIdTCGP": "SWSH08 Fusion Strike",
     "expName": "Fusion Strike",
     "expCardNumber": "110",
     "expCodeTCGP": "SWSH08",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/253268.jpg",
     "price": 0.04,
     "description": "",
     "releaseDate": "2021-11-12T00:00:00Z",
     "energyType": "Psychic",
     "cardType": "Pokemon",
     "pokedex": 39,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH06-Chilling-Reign-Diglett-076",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 241741,
     "name": "Diglett",
     "expIdTCGP": "SWSH06 Chilling Reign",
     "expName": "Chilling Reign",
     "expCardNumber": "076",
     "expCodeTCGP": "SWSH06",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/241741.jpg",
     "price": 0.02,
     "description": "",
     "releaseDate": "2021-06-18T00:00:00Z",
     "energyType": "Fighting",
     "cardType": "Pokemon",
     "pokedex": 50,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH08-Fusion-Strike-Meowth-199",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 253291,
     "name": "Meowth",
     "expIdTCGP": "SWSH08 Fusion Strike",
     "expName": "Fusion Strike",
     "expCardNumber": "199",
     "expCodeTCGP": "SWSH08",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/253291.jpg",
     "price": 0.02,
     "description": "",
     "releaseDate": "2021-11-12T00:00:00Z",
     "energyType": "Colorless",
     "cardType": "Pokemon",
     "pokedex": 52,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH08-Fusion-Strike-Galarian-Meowth-180",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 253326,
     "name": "Galarian Meowth",
     "expIdTCGP": "SWSH08 Fusion Strike",
     "expName": "Fusion Strike",
     "expCardNumber": "180",
     "expCodeTCGP": "SWSH08",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/253326.jpg",
     "price": 0.03,
     "description": "",
     "releaseDate": "2021-11-12T00:00:00Z",
     "energyType": "Metal",
     "cardType": "Pokemon",
     "pokedex": 52,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH07-Evolving-Skies-Golduck-025",
     "collection": "Extra",
     "variant": "Reverse Holofoil",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 246818,
     "name": "Golduck",
     "expIdTCGP": "SWSH07 Evolving Skies",
     "expName": "Evolving Skies",
     "expCardNumber": "025",
     "expCodeTCGP": "SWSH07",
     "rarity": "Uncommon",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/246818.jpg",
     "price": 0.04,
     "description": "",
     "releaseDate": "2021-08-27T00:00:00Z",
     "energyType": "Water",
     "cardType": "Pokemon",
     "pokedex": 55,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH08-Fusion-Strike-Mankey-133",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 253334,
     "name": "Mankey",
     "expIdTCGP": "SWSH08 Fusion Strike",
     "expName": "Fusion Strike",
     "expCardNumber": "133",
     "expCodeTCGP": "SWSH08",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/253334.jpg",
     "price": 0.02,
     "description": "",
     "releaseDate": "2021-11-12T00:00:00Z",
     "energyType": "Fighting",
     "cardType": "Pokemon",
     "pokedex": 56,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH08-Fusion-Strike-Growlithe-032",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 253129,
     "name": "Growlithe",
     "expIdTCGP": "SWSH08 Fusion Strike",
     "expName": "Fusion Strike",
     "expCardNumber": "032",
     "expCodeTCGP": "SWSH08",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/253129.jpg",
     "price": 0.04,
     "description": "",
     "releaseDate": "2021-11-12T00:00:00Z",
     "energyType": "Fire",
     "cardType": "Pokemon",
     "pokedex": 58,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH09-Brilliant-Stars-Farfetch'd-115",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 263838,
     "name": "Farfetch'd",
     "expIdTCGP": "SWSH09 Brilliant Stars",
     "expName": "Brilliant Stars",
     "expCardNumber": "115",
     "expCodeTCGP": "SWSH09",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/263838.jpg",
     "price": 0.02,
     "description": "",
     "releaseDate": "2022-02-25T00:00:00Z",
     "energyType": "Colorless",
     "cardType": "Pokemon",
     "pokedex": 83,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH03-Darkness-Ablaze-Muk-101",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 219402,
     "name": "Muk",
     "expIdTCGP": "SWSH03 Darkness Ablaze",
     "expName": "Darkness Ablaze",
     "expCardNumber": "101",
     "expCodeTCGP": "SWSH03",
     "rarity": "Rare",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/219402.jpg",
     "price": 0.14,
     "description": "",
     "releaseDate": "2020-08-14T00:00:00Z",
     "energyType": "Darkness",
     "cardType": "Pokemon",
     "pokedex": 89,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH02-Rebel-Clash-Voltorb-056",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 213137,
     "name": "Voltorb",
     "expIdTCGP": "SWSH02 Rebel Clash",
     "expName": "Rebel Clash",
     "expCardNumber": "056",
     "expCodeTCGP": "SWSH02",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/213137.jpg",
     "price": 0.04,
     "description": "",
     "releaseDate": "2020-05-01T00:00:00Z",
     "energyType": "Lightning",
     "cardType": "Pokemon",
     "pokedex": 100,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH09-Brilliant-Stars-Exeggcute-001",
     "collection": "Extra",
     "variant": "Reverse Holofoil",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 263578,
     "name": "Exeggcute",
     "expIdTCGP": "SWSH09 Brilliant Stars",
     "expName": "Brilliant Stars",
     "expCardNumber": "001",
     "expCodeTCGP": "SWSH09",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/263578.jpg",
     "price": 0.02,
     "description": "",
     "releaseDate": "2022-02-25T00:00:00Z",
     "energyType": "Grass",
     "cardType": "Pokemon",
     "pokedex": 102,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH06-Chilling-Reign-Koffing-094",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 241763,
     "name": "Koffing",
     "expIdTCGP": "SWSH06 Chilling Reign",
     "expName": "Chilling Reign",
     "expCardNumber": "094",
     "expCodeTCGP": "SWSH06",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/241763.jpg",
     "price": 0.03,
     "description": "",
     "releaseDate": "2021-06-18T00:00:00Z",
     "energyType": "Darkness",
     "cardType": "Pokemon",
     "pokedex": 109,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH09-Brilliant-Stars-Staryu-030",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 263729,
     "name": "Staryu",
     "expIdTCGP": "SWSH09 Brilliant Stars",
     "expName": "Brilliant Stars",
     "expCardNumber": "030",
     "expCodeTCGP": "SWSH09",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/263729.jpg",
     "price": 0.02,
     "description": "",
     "releaseDate": "2022-02-25T00:00:00Z",
     "energyType": "Water",
     "cardType": "Pokemon",
     "pokedex": 120,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH09-Brilliant-Stars-Magmar-019",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 263705,
     "name": "Magmar",
     "expIdTCGP": "SWSH09 Brilliant Stars",
     "expName": "Brilliant Stars",
     "expCardNumber": "019",
     "expCodeTCGP": "SWSH09",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/263705.jpg",
     "price": 0.02,
     "description": "",
     "releaseDate": "2022-02-25T00:00:00Z",
     "energyType": "Fire",
     "cardType": "Pokemon",
     "pokedex": 126,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH02-Rebel-Clash-Electabuzz-058",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 213139,
     "name": "Electabuzz",
     "expIdTCGP": "SWSH02 Rebel Clash",
     "expName": "Rebel Clash",
     "expCardNumber": "058",
     "expCodeTCGP": "SWSH02",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/213139.jpg",
     "price": 0.06,
     "description": "",
     "releaseDate": "2020-05-01T00:00:00Z",
     "energyType": "Lightning",
     "cardType": "Pokemon",
     "pokedex": 125,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH08-Fusion-Strike-Eevee-205",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 253300,
     "name": "Eevee",
     "expIdTCGP": "SWSH08 Fusion Strike",
     "expName": "Fusion Strike",
     "expCardNumber": "205",
     "expCodeTCGP": "SWSH08",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/253300.jpg",
     "price": 0.04,
     "description": "",
     "releaseDate": "2021-11-12T00:00:00Z",
     "energyType": "Colorless",
     "cardType": "Pokemon",
     "pokedex": 133,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH10-Astral-Radiance-Eevee-119",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 272353,
     "name": "Eevee",
     "expIdTCGP": "SWSH10 Astral Radiance",
     "expName": "Astral Radiance",
     "expCardNumber": "119",
     "expCodeTCGP": "SWSH10",
     "rarity": "Common",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/272353.jpg",
     "price": 0.11,
     "description": "Ability — Resonating Evolution\r\n<br>During your turn, if you played a card from your hand to evolve one of your other Eevee, you may search your deck for a card that evolves from that Pokémon and put it onto that Pokémon to evolve it. Then, shuffle your deck.",
     "releaseDate": "2022-05-27T00:00:00Z",
     "energyType": "Colorless",
     "cardType": "Pokemon",
     "pokedex": 133,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH06-Chilling-Reign-Flaaffy-048",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 241705,
     "name": "Flaaffy",
     "expIdTCGP": "SWSH06 Chilling Reign",
     "expName": "Chilling Reign",
     "expCardNumber": "048",
     "expCodeTCGP": "SWSH06",
     "rarity": "Uncommon",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/241705.jpg",
     "price": 0.03,
     "description": "",
     "releaseDate": "2021-06-18T00:00:00Z",
     "energyType": "Lightning",
     "cardType": "Pokemon",
     "pokedex": 180,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    },
    {
     "cardId": "SWSH03-Darkness-Ablaze-Granbull-071",
     "collection": "Extra",
     "variant": "Normal",
     "paid": 0,
     "count": 1,
     "grade": "",
     "idTCGP": 219446,
     "name": "Granbull",
     "expIdTCGP": "SWSH03 Darkness Ablaze",
     "expName": "Darkness Ablaze",
     "expCardNumber": "071",
     "expCodeTCGP": "SWSH03",
     "rarity": "Rare",
     "img": "https://product-images.tcgplayer.com/fit-in/437x437/219446.jpg",
     "price": 0.1,
     "description": "",
     "releaseDate": "2020-08-14T00:00:00Z",
     "energyType": "Psychic",
     "cardType": "Pokemon",
     "pokedex": 210,
     "variants": "[\"Normal\",\"Reverse Holofoil\"]"
    }]